config/routes.rb
Rails.application.routes.draw do

  get 'products/index'

  get 'products/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/404' => 'errors#not_found'
  get '/422' => 'errors#unprocessable_entity'
  get '/500' => 'errors#internal_server_error'

  resources :categories, only: :show do
    resources :products, only: :show
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories, class_name: 'Category',
           foreign_key: 'parent_category_id', dependent: :destroy
  has_many :products

  belongs_to :parent_category, class_name: 'Category'

  validates :title, presence: true, uniqueness: true

  mount_uploader :image, CategoryImageUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  validates :title, presence: true, uniqueness: true

  mount_uploader :image, ProductImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :parent_categories

  private

  def parent_categories
    Category.where(parent_category: nil).order(:position)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render(:status => 404)
  end

  def unprocessable_entity
    render(:status => 422)
  end

  def internal_server_error
    render(:status => 500)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/show.html.erb
<div class="container">

  <div class="col-md-12">

    <ul class="breadcrumb">
      <li><a href="#">Home</a>
      </li>
      <% if @category.parent_category %>
          <% if @category.parent_category.parent_category %>
              <li>
                <%= link_to @category.parent_category.parent_category.title, @category.parent_category.parent_category %>
              </li>
          <% end %>
          <li>
            <%= link_to @category.parent_category.title, @category.parent_category %>
          </li>
      <% end %>
      <li>
        <%= link_to @category.title, @category %>
      </li>
    </ul>

    <div class="box">
      <h1>Ladies</h1>

      <p>In our Ladies department we offer wide selection of the best products
        we have found and carefully selected worldwide.</p>
    </div>

    <div class="box info-bar">
      <div class="row">
        <div class="col-sm-12 col-md-4 products-showing">
          Showing <strong>12</strong> of <strong>25</strong> products
        </div>

        <div class="col-sm-12 col-md-8  products-number-sort">
          <div class="row">
            <form class="form-inline">
              <div class="col-md-6 col-sm-6">
                <div class="products-number">
                  <strong>Show</strong>
                  <a href="#" class="btn btn-default btn-sm btn-primary">12</a>
                  <a href="#" class="btn btn-default btn-sm">24</a>
                  <a href="#" class="btn btn-default btn-sm">All</a> products
                </div>
              </div>
              <div class="col-md-6 col-sm-6">
                <div class="products-sort-by">
                  <strong>Sort by</strong>
                  <select name="sort-by" class="form-control">
                    <option>Price</option>
                    <option>Name</option>
                    <option>Sales first</option>
                  </select>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <% if @category.products.count > 0 %>
        <div class="row products">
          <% @category.products.each do |product| %>
              <div class="col-md-3 col-sm-4">
                <div class="product">
                  <div class="flip-container">
                    <div class="flipper">
                      <div class="front">
                        <a href="<%= category_product_path(@category, product) %>">
                          <img src="/img/product2.jpg" alt="" class="img-responsive">
                        </a>
                      </div>
                      <div class="back">
                        <a href="<%= category_product_path(@category, product) %>">
                          <img src="/img/product2_2.jpg" alt="" class="img-responsive">
                        </a>
                      </div>
                    </div>
                  </div>
                  <a href="<%= category_product_path(@category, product) %>" class="invisible">
                    <img src="/img/product2.jpg" alt="" class="img-responsive">
                  </a>

                  <div class="text">
                    <h3>
                      <%= link_to product.title, category_product_path(@category, product) %>
                    </h3>

                    <p class="price">
                      <del>$280</del>
                      <%= number_to_currency(product.price) %>
                    </p>
                    <p class="buttons">
                      <a href="<%= category_product_path(@category, product) %>" class="btn btn-default">View
                        detail</a>
                      <a href="<%= category_product_path(@category, product) %>" class="btn btn-primary"><i class="fa fa-shopping-cart"></i>Add
                        to cart</a>
                    </p>
                  </div>
                  <!-- /.text -->

                  <div class="ribbon sale">
                    <div class="theribbon">SALE</div>
                    <div class="ribbon-background"></div>
                  </div>
                  <!-- /.ribbon -->

                  <div class="ribbon new">
                    <div class="theribbon">NEW</div>
                    <div class="ribbon-background"></div>
                  </div>
                  <!-- /.ribbon -->

                  <div class="ribbon gift">
                    <div class="theribbon">GIFT</div>
                    <div class="ribbon-background"></div>
                  </div>
                  <!-- /.ribbon -->
                </div>
                <!-- /.product -->
              </div>
          <% end %>

        </div>
        <!-- /.products -->
    <% else %>
        <h5>No products yet in this category.</h5>
    <% end %>
    <div class="pages">

      <p class="loadMore">
        <a href="#" class="btn btn-primary btn-lg"><i class="fa fa-chevron-down"></i>
          Load more</a>
      </p>

      <ul class="pagination">
        <li><a href="#">&laquo;</a>
        </li>
        <li class="active"><a href="#">1</a>
        </li>
        <li><a href="#">2</a>
        </li>
        <li><a href="#">3</a>
        </li>
        <li><a href="#">4</a>
        </li>
        <li><a href="#">5</a>
        </li>
        <li><a href="#">&raquo;</a>
        </li>
      </ul>
    </div>


  </div>
  <!-- /.col-md-9 -->

</div>
<!-- /.container -->

app/views/layouts/_copyright.html.erb
<div id="copyright">
  <div class="container">
    <div class="col-md-6">
      <p class="pull-left">© 2015 Your name goes here.</p>

    </div>
    <div class="col-md-6">
      <p class="pull-right">Template by
        <a href="http://bootstrapious.com/e-commerce-templates">Bootstrap
          Ecommerce Templates</a> with support from
        <a href="http://kakusei.cz">Designové předměty</a>
        <!-- Not removing these links is part of the licence conditions of the template. Thanks for understanding :) -->
      </p>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer" data-animate="fadeInUp">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <h4>Pages</h4>

        <ul>
          <li><a href="<%= page_path('text') %>">About us</a>
          </li>
          <li><a href="<%= page_path('text') %>">Terms and conditions</a>
          </li>
          <li><a href="<%= page_path('faq') %>">FAQ</a>
          </li>
          <li><a href="<%= page_path('contact') %>">Contact us</a>
          </li>
        </ul>

        <hr>

        <h4>User section</h4>

        <ul>
          <li>
            <a href="#" data-toggle="modal" data-target="#login-modal">Login</a>
          </li>
          <li><a href="<%= page_path('register') %>">Regiter</a>
          </li>
        </ul>

        <hr class="hidden-md hidden-lg hidden-sm">

      </div>
      <!-- /.col-md-3 -->

      <div class="col-md-3 col-sm-6">

        <h4>Top categories</h4>

        <h5>Men</h5>

        <ul>
          <li><a href="<%= page_path('category') %>">T-shirts</a>
          </li>
          <li><a href="<%= page_path('category') %>">Shirts</a>
          </li>
          <li><a href="<%= page_path('category') %>">Accessories</a>
          </li>
        </ul>

        <h5>Ladies</h5>
        <ul>
          <li><a href="<%= page_path('category') %>">T-shirts</a>
          </li>
          <li><a href="<%= page_path('category') %>">Skirts</a>
          </li>
          <li><a href="<%= page_path('category') %>">Pants</a>
          </li>
          <li><a href="<%= page_path('category') %>">Accessories</a>
          </li>
        </ul>

        <hr class="hidden-md hidden-lg">

      </div>
      <!-- /.col-md-3 -->

      <div class="col-md-3 col-sm-6">

        <h4>Where to find us</h4>

        <p><strong>Obaju Ltd.</strong>
          <br>13/25 New Avenue
          <br>New Heaven
          <br>45Y 73J
          <br>England
          <br>
          <strong>Great Britain</strong>
        </p>

        <a href="<%= page_path('contact') %>">Go to contact page</a>

        <hr class="hidden-md hidden-lg">

      </div>
      <!-- /.col-md-3 -->


      <div class="col-md-3 col-sm-6">

        <h4>Get the news</h4>

        <p class="text-muted">Pellentesque habitant morbi tristique senectus
          et netus et malesuada fames ac turpis egestas.</p>

        <form>
          <div class="input-group">

            <input type="text" class="form-control">

                                <span class="input-group-btn">

			    <button class="btn btn-default" type="button">Subscribe!</button>

			</span>

          </div>
          <!-- /input-group -->
        </form>

        <hr>

        <h4>Stay in touch</h4>

        <p class="social">
          <a href="#" class="facebook external" data-animate-hover="shake"><i class="fa fa-facebook"></i></a>
          <a href="#" class="twitter external" data-animate-hover="shake"><i class="fa fa-twitter"></i></a>
          <a href="#" class="instagram external" data-animate-hover="shake"><i class="fa fa-instagram"></i></a>
          <a href="#" class="gplus external" data-animate-hover="shake"><i class="fa fa-google-plus"></i></a>
          <a href="#" class="email external" data-animate-hover="shake"><i class="fa fa-envelope"></i></a>
        </p>


      </div>
      <!-- /.col-md-3 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
</div>
<!-- /#footer -->

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default yamm" role="navigation" id="navbar">
  <div class="container">
    <div class="navbar-header">

      <a class="navbar-brand home" href="<%= page_path('index') %>" data-animate-hover="bounce">
        <img src="/img/logo.png" alt="Obaju logo" class="hidden-xs">
        <img src="/img/logo-small.png" alt="Obaju logo" class="visible-xs"><span class="sr-only">Obaju - go to homepage</span>
      </a>

      <div class="navbar-buttons">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
          <span class="sr-only">Toggle navigation</span>
          <i class="fa fa-align-justify"></i>
        </button>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#search">
          <span class="sr-only">Toggle search</span>
          <i class="fa fa-search"></i>
        </button>
        <a class="btn btn-default navbar-toggle" href="<%= page_path('basket') %>">
          <i class="fa fa-shopping-cart"></i>
          <span class="hidden-xs">3 items in cart</span>
        </a>
      </div>
    </div>
    <!--/.navbar-header -->

    <div class="navbar-collapse collapse" id="navigation">

      <ul class="nav navbar-nav navbar-left">
        <li class="active"><a href="<%= page_path('index') %>">Home</a>
        </li>
        <% parent_categories.each do |category| %>
            <% if category.subcategories.count > 0 %>
                <li class="dropdown yamm-fw">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">
                    <%= category.title %>
                    <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li>
                      <div class="yamm-content">
                        <div class="row">
                          <% category.subcategories.order(:position).each do |subcategory| %>
                              <div class="col-sm-3">
                                <h5><%= subcategory.title %></h5>
                                <% unless subcategory.subcategories.empty? %>
                                    <ul>
                                      <% subcategory.subcategories.order(:position).each do |thirdsubcategory| %>
                                          <li>
                                            <%= link_to thirdsubcategory.title, thirdsubcategory %>
                                          </li>
                                      <% end %>
                                    </ul>
                                <% end %>
                              </div>
                          <% end %>
                        </div>
                      </div>
                      <!-- /.yamm-content -->
                    </li>
                  </ul>
            <% else %>
                <li><%= link_to category.title, category %></li>
            <% end %>

            </li>
        <% end %>

        <li class="dropdown yamm-fw">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="200">Template
            <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <div class="yamm-content">
                <div class="row">
                  <div class="col-sm-3">
                    <h5>Shop</h5>
                    <ul>
                      <li><a href="<%= page_path('index') %>">Homepage</a>
                      </li>
                      <li><a href="<%= page_path('category') %>">Category -
                        sidebar left</a>
                      </li>
                      <li>
                        <a href="<%= page_path('category-right') %>">Category -
                          sidebar
                          right</a>
                      </li>
                      <li>
                        <a href="<%= page_path('category-full') %>">Category -
                          full width</a>
                      </li>
                      <li>
                        <a href="<%= page_path('detail') %>">Product detail</a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <h5>User</h5>
                    <ul>
                      <li><a href="<%= page_path('register') %>">Register /
                        login</a>
                      </li>
                      <li><a href="<%= page_path('customer-orders') %>">Orders
                        history</a>
                      </li>
                      <li>
                        <a href="<%= page_path('customer-order') %>">Order
                          history detail</a>
                      </li>
                      <li>
                        <a href="<%= page_path('customer-wishlist') %>">Wishlist</a>
                      </li>
                      <li><a href="<%= page_path('customer-account') %>">Customer
                        account /
                        change password</a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <h5>Order process</h5>
                    <ul>
                      <li>
                        <a href="<%= page_path('basket') %>">Shopping cart</a>
                      </li>
                      <li>
                        <a href="<%= page_path('checkout1') %>">Checkout - step
                          1</a>
                      </li>
                      <li>
                        <a href="<%= page_path('checkout2') %>">Checkout - step
                          2</a>
                      </li>
                      <li>
                        <a href="<%= page_path('checkout3') %>">Checkout - step
                          3</a>
                      </li>
                      <li>
                        <a href="<%= page_path('checkout4') %>">Checkout - step
                          4</a>
                      </li>
                    </ul>
                  </div>
                  <div class="col-sm-3">
                    <h5>Pages and blog</h5>
                    <ul>
                      <li><a href="<%= page_path('blog') %>">Blog listing</a>
                      </li>
                      <li><a href="<%= page_path('post') %>">Blog Post</a>
                      </li>
                      <li><a href="<%= page_path('faq') %>">FAQ</a>
                      </li>
                      <li><a href="<%= page_path('text') %>">Text page</a>
                      </li>
                      <li>
                        <a href="<%= page_path('text-right') %>">Text page -
                          right sidebar</a>
                      </li>
                      <li><a href="<%= page_path('404') %>">404 page</a>
                      </li>
                      <li><a href="<%= page_path('contact') %>">Contact</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <!-- /.yamm-content -->
            </li>
          </ul>
        </li>
      </ul>

    </div>
    <!--/.nav-collapse -->

    <div class="navbar-buttons">

      <div class="navbar-collapse collapse right" id="basket-overview">
        <a href="<%= page_path('basket') %>" class="btn btn-primary navbar-btn"><i class="fa fa-shopping-cart"></i><span class="hidden-sm">3 items in cart</span></a>
      </div>
      <!--/.nav-collapse -->

      <div class="navbar-collapse collapse right" id="search-not-mobile">
        <button type="button" class="btn navbar-btn btn-primary" data-toggle="collapse" data-target="#search">
          <span class="sr-only">Toggle search</span>
          <i class="fa fa-search"></i>
        </button>
      </div>

    </div>

    <div class="collapse clearfix" id="search">

      <form class="navbar-form" role="search">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search">
                        <span class="input-group-btn">

			<button type="submit" class="btn btn-primary">
        <i class="fa fa-search"></i></button>

		    </span>
        </div>
      </form>

    </div>
    <!--/.nav-collapse -->

  </div>
  <!-- /.container -->
</div>
<!-- /#navbar -->

app/views/layouts/_topbar.html.erb
<div id="top">
  <div class="container">
    <div class="col-md-6 offer" data-animate="fadeInDown">
      <a href="#" class="btn btn-success btn-sm" data-animate-hover="shake">Offer
        of the day</a> <a href="#">Get flat 35% off on orders over $50!</a>
    </div>
    <div class="col-md-6" data-animate="fadeInDown">
      <ul class="menu">
        <li>
          <a href="#" data-toggle="modal" data-target="#login-modal">Login</a>
        </li>
        <li><a href="<%= page_path('register') %>">Register</a>
        </li>
        <li><a href="<%= page_path('contact') %>">Contact</a>
        </li>
        <li><a href="#">Recently viewed</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
    <div class="modal-dialog modal-sm">

      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="Login">Customer login</h4>
        </div>
        <div class="modal-body">
          <form action="<%= page_path('customer-orders') %>" method="post">
            <div class="form-group">
              <input type="text" class="form-control" id="email-modal" placeholder="email">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="password-modal" placeholder="password">
            </div>

            <p class="text-center">
              <button class="btn btn-primary"><i class="fa fa-sign-in"></i> Log
                in
              </button>
            </p>

          </form>

          <p class="text-center text-muted">Not registered yet?</p>

          <p class="text-center text-muted">
            <a href="<%= page_path('register') %>"><strong>Register now</strong></a>! It is
            easy and done in 1&nbsp;minute and gives you access to special
            discounts and much more!</p>

        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- *** TOPBAR ***
_________________________________________________________ -->
<%= render partial: 'layouts/topbar' %>

<!-- *** TOP BAR END *** -->

<!-- *** NAVBAR ***
_________________________________________________________ -->

<%= render partial: 'layouts/navbar' %>

<!-- *** NAVBAR END *** -->


<div id="all">

  <div id="content">

    <%= yield %>

  </div>
  <!-- /#content -->

  <!-- *** FOOTER ***
  _________________________________________________________ -->

  <%= render partial: 'layouts/footer' %>

  <!-- *** FOOTER END *** -->


  <!-- *** COPYRIGHT ***
  _________________________________________________________ -->

  <%= render partial: 'layouts/copyright' %>

  <!-- *** COPYRIGHT END *** -->


</div>
<!-- /#all -->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
<%= yield :custom_js %>

</body>
</html>

app/views/pages/basket.html.erb
<div class="container">

  <div class="col-md-12">
    <ul class="breadcrumb">
      <li><a href="#">Home</a>
      </li>
      <li>Shopping cart</li>
    </ul>
  </div>

  <div class="col-md-9" id="basket">

    <div class="box">

      <form method="post" action="<%= page_path('checkout1') %>">

        <h1>Shopping cart</h1>

        <p class="text-muted">You currently have 3 item(s) in your cart.</p>

        <div class="table-responsive">
          <table class="table">
            <thead>
            <tr>
              <th colspan="2">Product</th>
              <th>Quantity</th>
              <th>Unit price</th>
              <th>Discount</th>
              <th colspan="2">Total</th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td>
                <a href="#">
                  <img src="img/detailsquare.jpg" alt="White Blouse Armani">
                </a>
              </td>
              <td><a href="#">White Blouse Armani</a>
              </td>
              <td>
                <input type="number" value="2" class="form-control">
              </td>
              <td>$123.00</td>
              <td>$0.00</td>
              <td>$246.00</td>
              <td><a href="#"><i class="fa fa-trash-o"></i></a>
              </td>
            </tr>
            <tr>
              <td>
                <a href="#">
                  <img src="img/basketsquare.jpg" alt="Black Blouse Armani">
                </a>
              </td>
              <td><a href="#">Black Blouse Armani</a>
              </td>
              <td>
                <input type="number" value="1" class="form-control">
              </td>
              <td>$200.00</td>
              <td>$0.00</td>
              <td>$200.00</td>
              <td><a href="#"><i class="fa fa-trash-o"></i></a>
              </td>
            </tr>
            </tbody>
            <tfoot>
            <tr>
              <th colspan="5">Total</th>
              <th colspan="2">$446.00</th>
            </tr>
            </tfoot>
          </table>

        </div>
        <!-- /.table-responsive -->

        <div class="box-footer">
          <div class="pull-left">
            <a href="<%= page_path('category') %>" class="btn btn-default"><i class="fa fa-chevron-left"></i>
              Continue shopping</a>
          </div>
          <div class="pull-right">
            <button class="btn btn-default"><i class="fa fa-refresh"></i>
              Update basket
            </button>
            <button type="submit" class="btn btn-primary">Proceed to checkout
              <i class="fa fa-chevron-right"></i>
            </button>
          </div>
        </div>

      </form>

    </div>
    <!-- /.box -->


    <div class="row same-height-row">
      <div class="col-md-3 col-sm-6">
        <div class="box same-height">
          <h3>You may also like these products</h3>
        </div>
      </div>

      <div class="col-md-3 col-sm-6">
        <div class="product same-height">
          <div class="flip-container">
            <div class="flipper">
              <div class="front">
                <a href="<%= page_path('detail') %>">
                  <img src="img/product2.jpg" alt="" class="img-responsive">
                </a>
              </div>
              <div class="back">
                <a href="<%= page_path('detail') %>">
                  <img src="img/product2_2.jpg" alt="" class="img-responsive">
                </a>
              </div>
            </div>
          </div>
          <a href="<%= page_path('detail') %>" class="invisible">
            <img src="img/product2.jpg" alt="" class="img-responsive">
          </a>

          <div class="text">
            <h3>Fur coat</h3>

            <p class="price">$143</p>
          </div>
        </div>
        <!-- /.product -->
      </div>

      <div class="col-md-3 col-sm-6">
        <div class="product same-height">
          <div class="flip-container">
            <div class="flipper">
              <div class="front">
                <a href="<%= page_path('detail') %>">
                  <img src="img/product1.jpg" alt="" class="img-responsive">
                </a>
              </div>
              <div class="back">
                <a href="<%= page_path('detail') %>">
                  <img src="img/product1_2.jpg" alt="" class="img-responsive">
                </a>
              </div>
            </div>
          </div>
          <a href="<%= page_path('detail') %>" class="invisible">
            <img src="img/product1.jpg" alt="" class="img-responsive">
          </a>

          <div class="text">
            <h3>Fur coat</h3>

            <p class="price">$143</p>
          </div>
        </div>
        <!-- /.product -->
      </div>


      <div class="col-md-3 col-sm-6">
        <div class="product same-height">
          <div class="flip-container">
            <div class="flipper">
              <div class="front">
                <a href="<%= page_path('detail') %>">
                  <img src="img/product3.jpg" alt="" class="img-responsive">
                </a>
              </div>
              <div class="back">
                <a href="<%= page_path('detail') %>">
                  <img src="img/product3_2.jpg" alt="" class="img-responsive">
                </a>
              </div>
            </div>
          </div>
          <a href="<%= page_path('detail') %>" class="invisible">
            <img src="img/product3.jpg" alt="" class="img-responsive">
          </a>

          <div class="text">
            <h3>Fur coat</h3>

            <p class="price">$143</p>

          </div>
        </div>
        <!-- /.product -->
      </div>

    </div>


  </div>
  <!-- /.col-md-9 -->

  <div class="col-md-3">
    <div class="box" id="order-summary">
      <div class="box-header">
        <h3>Order summary</h3>
      </div>
      <p class="text-muted">Shipping and additional costs are calculated based
        on the values you have entered.</p>

      <div class="table-responsive">
        <table class="table">
          <tbody>
          <tr>
            <td>Order subtotal</td>
            <th>$446.00</th>
          </tr>
          <tr>
            <td>Shipping and handling</td>
            <th>$10.00</th>
          </tr>
          <tr>
            <td>Tax</td>
            <th>$0.00</th>
          </tr>
          <tr class="total">
            <td>Total</td>
            <th>$456.00</th>
          </tr>
          </tbody>
        </table>
      </div>

    </div>


    <div class="box">
      <div class="box-header">
        <h4>Coupon code</h4>
      </div>
      <p class="text-muted">If you have a coupon code, please enter it in the
        box below.</p>

      <form>
        <div class="input-group">

          <input type="text" class="form-control">

                                <span class="input-group-btn">

					<button class="btn btn-primary" type="button">
            <i class="fa fa-gift"></i></button>

				    </span>
        </div>
        <!-- /input-group -->
      </form>
    </div>

  </div>
  <!-- /.col-md-3 -->

</div>
<!-- /.container -->